Folders
espresso-org/aragon-datastore pull request #98
Opened 2019-01-02 15:34 UTC by macor161

2019-01-02 22:43 UTC, juslar requested changes
Impressive work, very nice job! 

I would also run the linter and clean the remaining random `console.log()` in the code before merging.

2019-01-02 22:43 UTC, juslar commented on contracts/libraries/FileLibrary.sol
> +    function initializeRootFoler(FileList storage _self) internal {
Mistake in the function name. Should be `initializeRootFolder`

2019-01-02 22:43 UTC, juslar commented on contracts/libraries/FileLibrary.sol
> +    function addFolder(FileList storage _self, string _storageRef, uint256 _parentFolderId) internal returns (uint fileId) {
We could combine the `addFolder` and `addFile` functions into one and pass `isFolder` as a parameter. This would save us a tiny bit in bytecode, don't know if it's worth it ¯\_(ツ)_/¯

2019-01-03 05:09 UTC, leftab commented on contracts/libraries/FileLibrary.sol
> +    function initializeRootFoler(FileList storage _self) internal {
Done! And console.log are now also gone :)

2019-01-03 05:09 UTC, leftab commented on contracts/libraries/FileLibrary.sol
> +    function addFolder(FileList storage _self, string _storageRef, uint256 _parentFolderId) internal returns (uint fileId) {
Good idea!

2019-01-03 05:10 UTC, leftab commented
Are the warnings from the linter still valid? 

```
WARNING: src/encryption-providers/aes.ts[6, 17]: expected parameter: 'opts' to have a typedef
WARNING: src/encryption-providers/aes.ts[9, 13]: The key 'length' is not sorted alphabetically
WARNING: src/encryption-providers/aes.ts[10, 1]: Exceeds maximum line length of 120
```

2019-01-03 16:14 UTC, juslar commented
Yes :)

2019-01-03 16:15 UTC, juslar approved these changes
Great!

2019-01-03 18:17 UTC, merged